name: Build

on:
  push:
    branches:
    - main
    tags:
      - v*.*.*
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '21'
    - run: yarn install --frozen-lockfile
    - run: yarn eslint
    - run: yarn stylelint

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '21'
    - run: yarn install --frozen-lockfile

    - run: yarn build --browsers=all
